### ISSUE TITLE
Port mapping has no defaults

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-docs#20]
[The docs](https://github.com/nanobox-io/nanobox-docs/blob/f56cecf5d3b6c81ae0b847c473bee1700e3b576b/source/domains-networking/port-mapping.html.md#ports) say that the example is the default port mapping, but afaik, there is none, other than 80/443 -> 8080
![image](https://cloud.githubusercontent.com/assets/2653109/22352603/1d6769b6-e3da-11e6-941d-0c70bec4b784.png)

**Comment by tylerflint** [comment]
Unless something has changed recently, tcp and udp (not http/s) port mapping can be specified in this manner. In doing so, these will register new services within portal. For http though, only 80/443 are provided and will redirect to 8080. Here is an example of the dns app, which uses tcp and udp instead of http: https://github.com/nanobox-io/nanobox-app-dns/blob/master/boxfile.yml#L16-L18

**Comment by glinton** [comment]
Right, the documentation is correct in showing *how* to map ports, but the '`(Default)`' is misleading. Every app does not have port 21 forwarded to 3420 by default or 53 -> 3000

**Comment by tylerflint** [comment]
Ah, I see what you mean. That makes sense.

**Comment by sanderson** [comment]
I've removed `(Default)` from the comment and will deploy soon.
